"""Feedback model - User feedback and issue reporting."""

from __future__ import annotations

from datetime import datetime
from enum import Enum
from typing import TYPE_CHECKING, Optional
from uuid import UUID, uuid4

from sqlalchemy import (
    CheckConstraint, ForeignKey, Index, Text, text
)
from sqlalchemy.dialects.postgresql import JSONB, TIMESTAMP, UUID as PG_UUID
from sqlalchemy.orm import Mapped, mapped_column, relationship

from .base import Base

if TYPE_CHECKING:
    from .user import Profile
    from .company import Company


class FeedbackCategory(str, Enum):
    """Feedback categories."""
    BUG = "bug"
    FEATURE_REQUEST = "feature_request"
    IMPROVEMENT = "improvement"
    QUESTION = "question"
    COMPLAINT = "complaint"
    PRAISE = "praise"
    OTHER = "other"


class FeedbackStatus(str, Enum):
    """Feedback lifecycle status."""
    NEW = "new"
    ACKNOWLEDGED = "acknowledged"
    IN_PROGRESS = "in_progress"
    RESOLVED = "resolved"
    WONT_FIX = "wont_fix"


class FeedbackPriority(str, Enum):
    """Feedback priority levels."""
    LOW = "low"
    MEDIUM = "medium"
    HIGH = "high"
    URGENT = "urgent"


class Feedback(Base):
    """
    User feedback and issue reporting.

    This model stores user feedback, bug reports, feature requests, and general
    issues with the platform. The AI agent automatically categorizes incoming feedback
    and helps users articulate their concerns.

    Workflow:
    1. User provides feedback to AI agent
    2. Agent categorizes and stores feedback (status: new)
    3. User can add more details (agent updates existing feedback)
    4. Product team reviews and updates status
    """

    __tablename__ = "feedback"

    # ========================================================================
    # IDENTIFICATION
    # ========================================================================
    id: Mapped[UUID] = mapped_column(
        PG_UUID(as_uuid=True), primary_key=True, default=uuid4
    )

    profile_id: Mapped[UUID] = mapped_column(
        PG_UUID(as_uuid=True), ForeignKey("profiles.id", ondelete="CASCADE")
    )
    # User who submitted the feedback

    company_id: Mapped[Optional[UUID]] = mapped_column(
        PG_UUID(as_uuid=True),
        ForeignKey("companies.id", ondelete="CASCADE"),
        nullable=True
    )
    # Optional: company context for feedback

    # ========================================================================
    # CATEGORIZATION (Auto-determined by AI)
    # ========================================================================
    category: Mapped[str] = mapped_column(Text)
    # bug, feature_request, improvement, question, complaint, praise, other

    priority: Mapped[str] = mapped_column(
        Text, server_default=text("'medium'::text")
    )
    # low, medium, high, urgent (auto-determined by AI based on content)

    # ========================================================================
    # FEEDBACK CONTENT
    # ========================================================================
    title: Mapped[str] = mapped_column(Text)
    # Short summary of feedback (auto-generated by AI)

    feedback: Mapped[str] = mapped_column(Text)
    # Detailed feedback from user

    conversation_context: Mapped[Optional[str]] = mapped_column(
        Text, nullable=True
    )
    # Additional conversation context captured by AI

    # ========================================================================
    # TECHNICAL CONTEXT
    # ========================================================================
    page_url: Mapped[Optional[str]] = mapped_column(Text, nullable=True)
    # URL where feedback was given (if from web)

    user_agent: Mapped[Optional[str]] = mapped_column(Text, nullable=True)
    # Browser/client information

    channel: Mapped[str] = mapped_column(
        Text, server_default=text("'chatkit'::text")
    )
    # How feedback was submitted: chatkit, whatsapp, web, api

    thread_id: Mapped[Optional[str]] = mapped_column(Text, nullable=True)
    # ChatKit thread ID for conversation reference

    # ========================================================================
    # STATUS MANAGEMENT
    # ========================================================================
    status: Mapped[str] = mapped_column(
        Text, server_default=text("'new'::text")
    )
    # new, acknowledged, in_progress, resolved, wont_fix

    # ========================================================================
    # ATTACHMENTS & METADATA
    # ========================================================================
    attachments: Mapped[Optional[list]] = mapped_column(
        JSONB, nullable=True, server_default=text("'[]'::jsonb")
    )
    # Screenshots or files attached to feedback

    extra_metadata: Mapped[Optional[dict]] = mapped_column(
        "metadata",  # Column name in database
        JSONB, nullable=True, server_default=text("'{}'::jsonb")
    )
    # Additional structured metadata (error logs, browser info, etc.)

    tags: Mapped[Optional[list]] = mapped_column(
        JSONB, nullable=True, server_default=text("'[]'::jsonb")
    )
    # Tags for filtering: ["ui", "slow", "mobile", "billing"]

    # ========================================================================
    # TEAM RESPONSE
    # ========================================================================
    admin_notes: Mapped[Optional[str]] = mapped_column(Text, nullable=True)
    # Internal notes from product/support team

    response_to_user: Mapped[Optional[str]] = mapped_column(Text, nullable=True)
    # Public response sent to user

    assigned_to_user_id: Mapped[Optional[UUID]] = mapped_column(
        PG_UUID(as_uuid=True),
        ForeignKey("profiles.id", ondelete="SET NULL"),
        nullable=True
    )
    # Team member assigned to handle this feedback

    resolved_at: Mapped[Optional[datetime]] = mapped_column(
        TIMESTAMP(timezone=True), nullable=True
    )
    # When feedback was resolved

    # ========================================================================
    # TIMESTAMPS
    # ========================================================================
    created_at: Mapped[datetime] = mapped_column(
        TIMESTAMP(timezone=True), server_default=text("now()")
    )

    updated_at: Mapped[datetime] = mapped_column(
        TIMESTAMP(timezone=True),
        server_default=text("now()")
    )
    # Last time feedback was updated (by user or team)

    # ========================================================================
    # CONSTRAINTS
    # ========================================================================
    __table_args__ = (
        # Valid categories
        CheckConstraint(
            "category = ANY (ARRAY["
            "'bug'::text, 'feature_request'::text, 'improvement'::text, "
            "'question'::text, 'complaint'::text, 'praise'::text, 'other'::text])",
            name="feedback_category_check",
        ),
        # Valid statuses
        CheckConstraint(
            "status = ANY (ARRAY["
            "'new'::text, 'acknowledged'::text, 'in_progress'::text, "
            "'resolved'::text, 'wont_fix'::text])",
            name="feedback_status_check",
        ),
        # Valid priorities
        CheckConstraint(
            "priority = ANY (ARRAY["
            "'low'::text, 'medium'::text, 'high'::text, 'urgent'::text])",
            name="feedback_priority_check",
        ),
        # Valid channels
        CheckConstraint(
            "channel = ANY (ARRAY["
            "'chatkit'::text, 'whatsapp'::text, 'web'::text, 'api'::text])",
            name="feedback_channel_check",
        ),
        # Indexes for efficient queries
        Index("ix_feedback_profile_id", "profile_id"),
        Index("ix_feedback_company_id", "company_id"),
        Index("ix_feedback_category", "category"),
        Index("ix_feedback_status", "status"),
        Index("ix_feedback_priority", "priority"),
        Index("ix_feedback_created_at", "created_at"),
        Index("ix_feedback_profile_status", "profile_id", "status"),
    )

    # ========================================================================
    # RELATIONSHIPS
    # ========================================================================
    profile: Mapped["Profile"] = relationship(
        "Profile",
        foreign_keys=[profile_id],
        back_populates="feedback_submitted"
    )

    company: Mapped[Optional["Company"]] = relationship(
        "Company", back_populates="feedback"
    )

    assigned_to: Mapped[Optional["Profile"]] = relationship(
        "Profile",
        foreign_keys=[assigned_to_user_id],
        back_populates="feedback_assigned"
    )
