"""Tools for feedback submission and management."""

from __future__ import annotations

import logging
from datetime import datetime
from typing import Any

from agents import RunContextWrapper, function_tool

from app.agents.core import FizkoContext
from app.agents.tools.utils import get_supabase

logger = logging.getLogger(__name__)


@function_tool(strict_mode=False)
async def submit_feedback(
    ctx: RunContextWrapper[FizkoContext],
    category: str,
    title: str,
    feedback: str,
    priority: str = "medium",
    conversation_context: str | None = None,
) -> dict[str, Any]:
    """
    Submit user feedback, bug report, or feature request.

    Use this tool when the user wants to report a problem, suggest an improvement,
    or share feedback about the platform. The category and priority should be
    auto-determined by analyzing the user's message.

    **IMPORTANT: Category Detection Guidelines:**
    - **bug**: User reports something not working correctly, errors, crashes
      Examples: "El botón no funciona", "Aparece un error", "No puedo cargar los documentos"

    - **feature_request**: User wants a new capability that doesn't exist
      Examples: "Sería bueno poder...", "Me gustaría que tuvieran...", "Podrían agregar..."

    - **improvement**: User wants to enhance existing functionality
      Examples: "Esto podría ser más rápido", "Sería mejor si...", "El diseño podría mejorar"

    - **question**: User has a question about how something works (that you can't answer)
      Examples: "¿Por qué funciona así?", "No entiendo esto", "¿Es esto normal?"

    - **complaint**: User is frustrated or unhappy with something
      Examples: "Esto es muy lento", "No me gusta...", "Es confuso"

    - **praise**: User is happy and wants to compliment
      Examples: "Me encanta esta función", "Muy bueno!", "Excelente trabajo"

    - **other**: Doesn't fit other categories

    **Priority Detection Guidelines:**
    - **urgent**: Critical issues blocking work, data loss, security issues
    - **high**: Important problems affecting main workflows
    - **medium**: Regular feedback, minor issues (DEFAULT)
    - **low**: Nice-to-have suggestions, minor cosmetic issues

    Args:
        category: Feedback category (required). One of:
            - "bug" = Something is broken or not working
            - "feature_request" = Request for new functionality
            - "improvement" = Suggestion to improve existing feature
            - "question" = Question about the platform
            - "complaint" = General complaint or frustration
            - "praise" = Positive feedback
            - "other" = Other feedback
        title: Short summary of feedback (auto-generated by you from user's message)
            Should be concise (5-10 words) and descriptive
            Examples: "Error loading documents", "Add export to Excel feature"
        feedback: Detailed feedback content (user's full explanation)
            Include everything the user said about the issue
        priority: Priority level (default: "medium"). One of:
            - "urgent" = Critical blocking issue
            - "high" = Important problem
            - "medium" = Normal feedback (default)
            - "low" = Nice to have
        conversation_context: Optional additional context from the conversation
            Use this to capture relevant details that help understand the feedback

    Returns:
        Dictionary with created feedback details including feedback_id for future updates

    Examples:
        User: "El botón de descarga no funciona, aparece un error"
        Tool call: submit_feedback(
            category="bug",
            title="Error en botón de descarga",
            feedback="El botón de descarga no funciona, aparece un error",
            priority="high"
        )

        User: "Sería genial poder exportar los datos a Excel"
        Tool call: submit_feedback(
            category="feature_request",
            title="Exportar datos a Excel",
            feedback="Sería genial poder exportar los datos a Excel",
            priority="medium"
        )

        User: "Me encanta la nueva interfaz, muy intuitiva!"
        Tool call: submit_feedback(
            category="praise",
            title="Nueva interfaz muy intuitiva",
            feedback="Me encanta la nueva interfaz, muy intuitiva!",
            priority="low"
        )
    """
    user_id = ctx.context.request_context.get("user_id")
    if not user_id:
        return {"error": "Usuario no autenticado"}

    # Normalize user_id - convert "anonymous" or "unknown" to None
    if user_id in ("anonymous", "unknown"):
        return {"error": "Usuario no autenticado - no se puede enviar feedback como anónimo"}

    company_id = ctx.context.request_context.get("company_id")
    # Normalize company_id - convert "anonymous" or "unknown" to None
    if company_id in ("anonymous", "unknown", ""):
        company_id = None

    thread_id = ctx.context.request_context.get("thread_id")
    channel = ctx.context.request_context.get("channel", "chatkit")

    # Validate category
    valid_categories = [
        "bug", "feature_request", "improvement",
        "question", "complaint", "praise", "other"
    ]
    if category not in valid_categories:
        return {
            "error": "Categoría inválida",
            "message": (
                f"❌ La categoría '{category}' no es válida.\n\n"
                f"Categorías disponibles:\n"
                f"• bug - Algo no funciona correctamente\n"
                f"• feature_request - Solicitud de nueva funcionalidad\n"
                f"• improvement - Mejora a funcionalidad existente\n"
                f"• question - Pregunta sobre la plataforma\n"
                f"• complaint - Queja o frustración\n"
                f"• praise - Comentario positivo\n"
                f"• other - Otro tipo de feedback"
            ),
        }

    # Validate priority
    valid_priorities = ["low", "medium", "high", "urgent"]
    if priority not in valid_priorities:
        priority = "medium"  # Default to medium if invalid

    try:
        supabase = get_supabase()

        # Create feedback
        new_feedback = await supabase.feedback.create(
            profile_id=user_id,
            company_id=company_id,  # Already normalized to None if anonymous
            category=category,
            priority=priority,
            title=title,
            feedback=feedback,
            conversation_context=conversation_context,
            channel=channel,
            thread_id=thread_id,
        )

        if not new_feedback:
            return {"error": "Error al crear feedback"}

        # Map category to Spanish for user response
        category_labels = {
            "bug": "Error/Bug",
            "feature_request": "Solicitud de funcionalidad",
            "improvement": "Mejora",
            "question": "Pregunta",
            "complaint": "Queja",
            "praise": "Comentario positivo",
            "other": "Otro",
        }

        priority_labels = {
            "urgent": "Urgente",
            "high": "Alta",
            "medium": "Media",
            "low": "Baja",
        }

        return {
            "success": True,
            "feedback_id": new_feedback.get("id"),
            "category": category,
            "category_label": category_labels.get(category, category),
            "priority": priority,
            "priority_label": priority_labels.get(priority, priority),
            "title": title,
            "status": "new",
            "message": (
                f"✅ Feedback registrado exitosamente!\n\n"
                f"📋 **{title}**\n"
                f"Categoría: {category_labels.get(category, category)}\n"
                f"Prioridad: {priority_labels.get(priority, priority)}\n\n"
                f"Gracias por tu feedback. Nuestro equipo lo revisará pronto.\n\n"
                f"Si necesitas agregar más detalles, puedes decirme y actualizaré este feedback."
            ),
        }

    except Exception as e:
        logger.error(f"Error creating feedback: {e}")
        return {"error": f"Error al crear feedback: {str(e)}"}


@function_tool(strict_mode=False)
async def update_feedback(
    ctx: RunContextWrapper[FizkoContext],
    feedback_id: str,
    additional_info: str,
) -> dict[str, Any]:
    """
    Update existing feedback with additional information.

    Use this tool ONLY when the user explicitly wants to add more details to
    feedback they just submitted. This allows users to clarify or expand on
    their original feedback without creating duplicate entries.

    **When to use:**
    - User says "también quiero agregar que..." after submitting feedback
    - User provides more context: "ah, y también pasa cuando..."
    - User remembers additional details: "olvidé mencionar que..."

    **When NOT to use:**
    - For completely new/different feedback (use submit_feedback instead)
    - To change the category or priority (those are set automatically)
    - For feedback older than the current conversation

    Args:
        feedback_id: ID of the feedback to update (from submit_feedback response)
        additional_info: New information to append to existing feedback
            This will be added to the feedback content, not replace it

    Returns:
        Dictionary with updated feedback details

    Examples:
        [After submitting feedback with id="abc-123"]
        User: "Ah, también quiero agregar que esto pasa solo en Chrome"
        Tool call: update_feedback(
            feedback_id="abc-123",
            additional_info="También pasa solo en Chrome"
        )

        User: "Olvidé mencionar que el error aparece al hacer click en guardar"
        Tool call: update_feedback(
            feedback_id="abc-123",
            additional_info="El error aparece específicamente al hacer click en guardar"
        )
    """
    user_id = ctx.context.request_context.get("user_id")
    if not user_id:
        return {"error": "Usuario no autenticado"}

    # Normalize user_id - convert "anonymous" or "unknown" to None
    if user_id in ("anonymous", "unknown"):
        return {"error": "Usuario no autenticado - no se puede actualizar feedback como anónimo"}

    try:
        supabase = get_supabase()

        # Get existing feedback
        existing_feedback = await supabase.feedback.get_by_id(
            feedback_id=feedback_id,
            profile_id=user_id
        )

        if not existing_feedback:
            return {
                "error": "Feedback no encontrado",
                "message": (
                    "❌ No pude encontrar ese feedback. "
                    "Solo puedes actualizar feedback que hayas enviado recientemente en esta conversación."
                ),
            }

        # Can only update feedback that's not yet resolved
        status = existing_feedback.get("status")
        if status not in ["new", "acknowledged"]:
            return {
                "error": "No se puede actualizar",
                "message": (
                    f"❌ Este feedback ya fue {status} "
                    f"y no se puede actualizar. Si tienes nuevo feedback, "
                    f"puedo crear uno nuevo."
                ),
            }

        # Append additional info to existing feedback
        updated_content = (
            f"{existing_feedback.get('feedback')}\n\n"
            f"**Información adicional:**\n{additional_info}"
        )

        # Update feedback
        updated = await supabase.feedback.update(
            feedback_id=feedback_id,
            feedback=updated_content,
            updated_at=datetime.now().isoformat()
        )

        if not updated:
            return {"error": "Error al actualizar feedback"}

        return {
            "success": True,
            "feedback_id": updated.get("id"),
            "title": updated.get("title"),
            "updated_content": updated_content,
            "message": (
                f"✅ Feedback actualizado!\n\n"
                f"📋 **{updated.get('title')}**\n\n"
                f"Agregué la información adicional. "
                f"Si necesitas agregar más detalles, avísame."
            ),
        }

    except ValueError:
        return {"error": "ID de feedback inválido"}
    except Exception as e:
        logger.error(f"Error updating feedback: {e}")
        return {"error": f"Error al actualizar feedback: {str(e)}"}


@function_tool(strict_mode=False)
async def get_my_feedback(
    ctx: RunContextWrapper[FizkoContext],
    status: str | None = None,
    limit: int = 10,
) -> dict[str, Any]:
    """
    Get list of user's submitted feedback.

    Use this tool when the user wants to see their feedback history or
    check the status of previously submitted feedback.

    Args:
        status: Optional filter by status:
            - "new" = Recién enviado, sin revisar
            - "acknowledged" = Recibido por el equipo
            - "in_progress" = En proceso de resolución
            - "resolved" = Resuelto
            - "wont_fix" = No se implementará
        limit: Maximum number of feedback to return (default: 10, max: 50)

    Returns:
        List of user's feedback with details

    Examples:
        User: "¿Qué pasó con el feedback que envié?"
        Tool call: get_my_feedback()

        User: "Muéstrame mis bugs reportados"
        Tool call: get_my_feedback(status="new")
    """
    user_id = ctx.context.request_context.get("user_id")
    if not user_id:
        return {"error": "Usuario no autenticado"}

    # Validate limit
    if limit > 50:
        limit = 50

    try:
        supabase = get_supabase()

        # Validate status
        if status:
            valid_statuses = ["new", "acknowledged", "in_progress", "resolved", "wont_fix"]
            if status not in valid_statuses:
                return {
                    "error": "Estado inválido",
                    "message": f"Estado debe ser uno de: {', '.join(valid_statuses)}",
                }

        # Get feedback list
        feedback_list = await supabase.feedback.list_by_profile(
            profile_id=user_id,
            status=status,
            limit=limit
        )

        if not feedback_list:
            return {
                "feedback": [],
                "total_count": 0,
                "message": (
                    "No tienes feedback registrado aún.\n\n"
                    "Si encuentras algún problema o tienes sugerencias, "
                    "¡no dudes en contármelo!"
                ),
            }

        # Format feedback for response
        category_labels = {
            "bug": "Error/Bug",
            "feature_request": "Solicitud de funcionalidad",
            "improvement": "Mejora",
            "question": "Pregunta",
            "complaint": "Queja",
            "praise": "Comentario positivo",
            "other": "Otro",
        }

        status_labels = {
            "new": "Nuevo",
            "acknowledged": "Recibido",
            "in_progress": "En proceso",
            "resolved": "Resuelto",
            "wont_fix": "No se implementará",
        }

        formatted_feedback = []
        for fb in feedback_list:
            formatted_feedback.append({
                "id": fb.get("id"),
                "title": fb.get("title"),
                "category": fb.get("category"),
                "category_label": category_labels.get(fb.get("category"), fb.get("category")),
                "priority": fb.get("priority"),
                "status": fb.get("status"),
                "status_label": status_labels.get(fb.get("status"), fb.get("status")),
                "created_at": fb.get("created_at"),
                "response": fb.get("response_to_user"),
            })

        return {
            "feedback": formatted_feedback,
            "total_count": len(formatted_feedback),
            "filters_applied": {"status": status} if status else {},
            "message": (
                f"📋 Tienes {len(formatted_feedback)} feedback registrado(s).\n\n"
                f"Usa este historial para revisar el estado de tus reportes anteriores."
            ),
        }

    except Exception as e:
        logger.error(f"Error getting feedback: {e}")
        return {"error": f"Error al obtener feedback: {str(e)}"}
