-- Migration: Create feedback table for user feedback and issue reporting
-- Description: Allow users to submit feedback, bug reports, feature requests through AI agent

-- Create feedback table
CREATE TABLE IF NOT EXISTS feedback (
    -- Identification
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    profile_id UUID NOT NULL REFERENCES profiles(id) ON DELETE CASCADE,
    company_id UUID REFERENCES companies(id) ON DELETE CASCADE,

    -- Categorization (auto-determined by AI agent)
    category TEXT NOT NULL CHECK (category IN (
        'bug',
        'feature_request',
        'improvement',
        'question',
        'complaint',
        'praise',
        'other'
    )),
    priority TEXT NOT NULL DEFAULT 'medium' CHECK (priority IN (
        'low',
        'medium',
        'high',
        'urgent'
    )),

    -- Feedback content
    title TEXT NOT NULL,
    feedback TEXT NOT NULL,
    conversation_context TEXT,

    -- Technical context
    page_url TEXT,
    user_agent TEXT,
    channel TEXT NOT NULL DEFAULT 'chatkit' CHECK (channel IN (
        'chatkit',
        'whatsapp',
        'web',
        'api'
    )),
    thread_id TEXT,

    -- Status management
    status TEXT NOT NULL DEFAULT 'new' CHECK (status IN (
        'new',
        'acknowledged',
        'in_progress',
        'resolved',
        'wont_fix'
    )),

    -- Attachments & metadata (JSONB for flexibility)
    attachments JSONB DEFAULT '[]'::jsonb,
    metadata JSONB DEFAULT '{}'::jsonb,
    tags JSONB DEFAULT '[]'::jsonb,

    -- Team response
    admin_notes TEXT,
    response_to_user TEXT,
    assigned_to_user_id UUID REFERENCES profiles(id) ON DELETE SET NULL,
    resolved_at TIMESTAMPTZ,

    -- Timestamps
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- Create indexes for efficient queries
CREATE INDEX IF NOT EXISTS ix_feedback_profile_id ON feedback(profile_id);
CREATE INDEX IF NOT EXISTS ix_feedback_company_id ON feedback(company_id);
CREATE INDEX IF NOT EXISTS ix_feedback_category ON feedback(category);
CREATE INDEX IF NOT EXISTS ix_feedback_status ON feedback(status);
CREATE INDEX IF NOT EXISTS ix_feedback_priority ON feedback(priority);
CREATE INDEX IF NOT EXISTS ix_feedback_created_at ON feedback(created_at);
CREATE INDEX IF NOT EXISTS ix_feedback_profile_status ON feedback(profile_id, status);

-- Enable Row Level Security
ALTER TABLE feedback ENABLE ROW LEVEL SECURITY;

-- RLS Policies for feedback

-- 1. Users can see their own feedback
CREATE POLICY "Users can view own feedback"
ON feedback
FOR SELECT
USING (
    auth.uid() = profile_id
);

-- 2. Users can insert their own feedback
CREATE POLICY "Users can create own feedback"
ON feedback
FOR INSERT
WITH CHECK (
    auth.uid() = profile_id
);

-- 3. Users can update their own feedback (before it's resolved)
CREATE POLICY "Users can update own feedback"
ON feedback
FOR UPDATE
USING (
    auth.uid() = profile_id
    AND status IN ('new', 'acknowledged')
)
WITH CHECK (
    auth.uid() = profile_id
);

-- 4. Service role can do everything (for AI agent)
CREATE POLICY "Service role has full access to feedback"
ON feedback
FOR ALL
USING (
    auth.jwt()->>'role' = 'service_role'
)
WITH CHECK (
    auth.jwt()->>'role' = 'service_role'
);

-- Create function to auto-update updated_at timestamp
CREATE OR REPLACE FUNCTION update_feedback_updated_at()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = now();
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Create trigger for updated_at
CREATE TRIGGER feedback_updated_at_trigger
    BEFORE UPDATE ON feedback
    FOR EACH ROW
    EXECUTE FUNCTION update_feedback_updated_at();

-- Add comment to table
COMMENT ON TABLE feedback IS 'User feedback, bug reports, and feature requests collected via AI agent';
COMMENT ON COLUMN feedback.category IS 'AI-determined category: bug, feature_request, improvement, question, complaint, praise, other';
COMMENT ON COLUMN feedback.priority IS 'AI-determined priority level based on content urgency';
COMMENT ON COLUMN feedback.title IS 'Short summary auto-generated by AI from feedback content';
COMMENT ON COLUMN feedback.conversation_context IS 'Additional context captured from the conversation by AI';
COMMENT ON COLUMN feedback.channel IS 'Source channel: chatkit (web chat), whatsapp, web (form), api';
